// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmgfuXovmOTXAyF0KeP0Bv0wCx1LHvHCg',
    appId: '1:575784813165:web:d9748d3a951af05485b564',
    messagingSenderId: '575784813165',
    projectId: 'vitalh3alth',
    authDomain: 'vitalh3alth.firebaseapp.com',
    storageBucket: 'vitalh3alth.appspot.com',
    measurementId: 'G-G8HXB9KP9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGsAGfUlUJ-EChB2zgpiEvVrvxOUH_Udk',
    appId: '1:575784813165:android:4a8691eafec2693a85b564',
    messagingSenderId: '575784813165',
    projectId: 'vitalh3alth',
    storageBucket: 'vitalh3alth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFDH-GK-uPBLdx3Kc9Cn82Iv0QNm9c-Q',
    appId: '1:575784813165:ios:2d0fefe26f4b676d85b564',
    messagingSenderId: '575784813165',
    projectId: 'vitalh3alth',
    storageBucket: 'vitalh3alth.appspot.com',
    androidClientId: '575784813165-cjbatcsnpdgk1snijeiqf9te2jdd03ao.apps.googleusercontent.com',
    iosClientId: '575784813165-q09jeo9kkgi82e7ne94uuqo48pb4bl82.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFDH-GK-uPBLdx3Kc9Cn82Iv0QNm9c-Q',
    appId: '1:575784813165:ios:2d0fefe26f4b676d85b564',
    messagingSenderId: '575784813165',
    projectId: 'vitalh3alth',
    storageBucket: 'vitalh3alth.appspot.com',
    androidClientId: '575784813165-cjbatcsnpdgk1snijeiqf9te2jdd03ao.apps.googleusercontent.com',
    iosClientId: '575784813165-q09jeo9kkgi82e7ne94uuqo48pb4bl82.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmgfuXovmOTXAyF0KeP0Bv0wCx1LHvHCg',
    appId: '1:575784813165:web:f3aa984eeea77c3685b564',
    messagingSenderId: '575784813165',
    projectId: 'vitalh3alth',
    authDomain: 'vitalh3alth.firebaseapp.com',
    storageBucket: 'vitalh3alth.appspot.com',
    measurementId: 'G-094BEJN6ER',
  );
}
